backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        create: false
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "layouts/home.html",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "SEO Meta Description",
              name: "metaDesc",
              widget: "string",
              required: false,
            }
          - {
              label: "Intro",
              name: "intro",
              widget: "markdown",
              required: false,
            }
          - {
              label: "Featured Image",
              name: "featureImage",
              widget: "markdown",
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Case Study 1",
              name: "casestudy1",
              widget: "relation",
              collection: "casestudy",
              search_fields: ["title"],
              value_field: "title",
              display_fields: ["title"],
            }
          - {
              label: "Case Study 2",
              name: "casestudy2",
              widget: "relation",
              collection: "casestudy",
              search_fields: ["title"],
              value_field: "title",
              display_fields: ["title"],
            }
      - name: "services"
        label: "Services"
        delete: false
        file: "src/services.md"
        slug: "{{slug}}"
        create: false
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "layouts/about.html",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "SEO Meta Description",
              name: "metaDesc",
              widget: "string",
              required: false,
            }
          - {
              label: "Sub Title",
              name: "subtitle",
              widget: "markdown",
              required: false,
            }
          - {
              label: "Intro",
              name: "intro",
              widget: "markdown",
              required: false,
            }
          - {
              label: "Featured Image",
              name: "featureImage",
              widget: "image",
              required: false,
            }
          - {
              label: "Image 1",
              name: "image1",
              widget: "image",
              required: false,
            }
          - {
              label: "Image 2",
              name: "image2",
              widget: "image",
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    slug: "{{slug}}"
    preview_path: "posts/{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "services"
    label: "Services"
    folder: "src/services"
    slug: "{{slug}}"
    preview_path: "services/{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Data"
        name: "site_data"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {
              label: "Telephone",
              name: "telephone",
              widget: "string",
              required: false,
            }
          - { label: "Email", name: "email", widget: "string", required: false }
          - {
              label: "Twitter Handle",
              name: "twitter",
              widget: "string",
              required: false,
            }
          - {
              label: "Linkedin Handle",
              name: "linkedin",
              widget: "string",
              required: false,
            }
          - {
              label: "Availability",
              name: "availability",
              widget: "string",
              required: false,
            }
          - {
              label: "Contact Link",
              name: "contactlink",
              widget: "string",
              required: false,
            }
          - {
              label: "Contact Link Text",
              name: "contactlinktext",
              widget: "string",
              required: false,
            }
      - label: "Main Navigation"
        name: "main nav"
        delete: false
        file: "src/_data/navigation.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
      - label: "Footer Navigation"
        name: "bottom nav"
        delete: false
        file: "src/_data/footer_navigation.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
